# Generated by Django 4.2.5 on 2023-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, False), (2, False), (3, False), (4, False), (5, False)], default=1),
        ),
    ]
